### ISSUE TITLE
Propagate type information in Boogie

### ISSUE THREAD

**Issue by m7nu3l** [m7nu3l/TinyBCT#29]
When using an open entry point (method with parameters), if we use objects from the heap, there aren´t any assumptions about its type. By propagating information from method parameters and load instructions, we can work around this.

**Comment by m7nu3l** [comment]
We may need to add an ensure property in the declaration of every extern procedure (if it is possible).

**Comment by m7nu3l** [comment]
https://github.com/m7nu3l/TinyBCT/commit/aa58fae42dc49e3d79e8b2e2e89a94e762e30f35  Example

**Comment by m7nu3l** [comment]
In https://github.com/m7nu3l/TinyBCT/commit/833180975c5600c7b63d6b0b357a727fabfea570  I added an ensure for every extern procedure that has a return value as Ref. 

A new problem arises and "TestListSumOK" is not working. I think the issue is regarding generics. Here are the details of the failure.

```
procedure {:extern} System.Collections.Generic.List`1.get_Item$System.Int32(this : Ref,index : int) returns ($result : Ref);
	ensures $Subtype($DynamicType($result), T$T());

procedure {:extern} System.Collections.Generic.List`1.get_Item$System.Int32($this: Ref, index$in: int) returns ($result: Union)
{
    $result := listContents[$this][index$in];
}
```

Corral reports that the ensure property is not met. Any ideas?

**Comment by m7nu3l** [comment]
Related to issue https://github.com/m7nu3l/TinyBCT/issues/37

**Comment by m7nu3l** [comment]
@rcastano  

The dyanmic dispatch chain was changed here 9243c77. There I also implemented the assume of the subtype for arguments if they are not null.

However the assume ref == null || Subtype(...) is still missing for extern procedure calls and cast operations.

**Comment by rcastano** [comment]
Fixed in https://github.com/m7nu3l/TinyBCT/commit/2c07a942196c350377a23670cb8e3b0742c7f2c0.
