### ISSUE TITLE
Missing file?

### ISSUE THREAD

**Issue by rcastano** [m7nu3l/TinyBCT#30]
Missing file in tests:
"Source file 'C:\Users\Doc\repos\TinyBCT\Test\Loops.cs' could not be found."

**Comment by rcastano** [comment]
Adding placeholder so that the project compiles (https://github.com/m7nu3l/TinyBCT/commit/a27c5561d692414132074266f44eb4efb91190dc). Please replace with the actual file.

**Comment by m7nu3l** [comment]
Fixed.
