### ISSUE TITLE
Fix defensive assert at the end of dynamic dispatch chain

### ISSUE THREAD

**Issue by rcastano** [m7nu3l/TinyBCT#37]
Use `if (ref != null) assert false;` instead of just `assert false;`.

**Comment by m7nu3l** [comment]
https://github.com/m7nu3l/TinyBCT/commit/9243c77072f6f2ac72bd13a33713d4eda10f82ee

The assume ref != null || Subtype still is missing from external calls and cast operations.

**Comment by m7nu3l** [comment]
I close this issue and I write the missing features in #29.
